api_platform:
  formats:
    jsonld: ['application/ld+json']
    json: ['application/json']
    html: ['text/html']
    jsonhal: ['application/hal+json']

  # defaults:
  #   stateless: true

  swagger:
    api_keys:
      # overridden in OpenApiFactoryDecorator
      access_token:
        name: Authorization
        type: header

when@prod:
  api_platform:
    enable_docs: false
    enable_entrypoint: false
    enable_swagger: false
    enable_swagger_ui: false
